apiVersion: apps/v1
kind: Deployment
metadata:
  name: brenox-engine
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/brainart16/brenox/brenox-engine:latest
