apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - ingress.yaml

secretGenerator:
  - name: brenox-secrets
    options:
      disableNameSuffixHash: true
    literals:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=dev-secret-change-me-k8s-only
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: job-migrate-patch.yaml
