apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: brenox

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - job-migrate.yaml

labels:
  - pairs:
      app.kubernetes.io/name: brenox
      app.kubernetes.io/part-of: brenox-engine
    includeSelectors: true
