// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSandboxAppUsers = `-- name: CountSandboxAppUsers :one
SELECT COUNT(*)::BIGINT
FROM app_users
WHERE app_id = $1
  AND environment = 'sandbox'
`

func (q *Queries) CountSandboxAppUsers(ctx context.Context, appID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSandboxAppUsers, appID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSandboxWorkspaceChannels = `-- name: CountSandboxWorkspaceChannels :one
SELECT COUNT(*)::BIGINT
FROM channels
WHERE workspace_id = $1
`

func (q *Queries) CountSandboxWorkspaceChannels(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSandboxWorkspaceChannels, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countWorkspaceMessages = `-- name: CountWorkspaceMessages :one
SELECT COUNT(*)::BIGINT
FROM messages m
JOIN channels c ON c.id = m.channel_id
WHERE c.workspace_id = $1
`

func (q *Queries) CountWorkspaceMessages(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMessages, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    app_id,
    name,
    key_prefix,
    key_hash,
    is_sandbox,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, app_id, name, key_prefix, key_hash, is_sandbox, created_at, revoked_at, last_used_at, expires_at
`

type CreateAPIKeyParams struct {
	AppID     int64
	Name      string
	KeyPrefix string
	KeyHash   string
	IsSandbox bool
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.AppID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.IsSandbox,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.IsSandbox,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createApp = `-- name: CreateApp :one
INSERT INTO apps (
    name,
    slug,
    workspace_id,
    sandbox_workspace_id,
    owner_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, slug, workspace_id, owner_id, created_at, allowed_origins, sandbox_workspace_id
`

type CreateAppParams struct {
	Name               string
	Slug               string
	WorkspaceID        int64
	SandboxWorkspaceID int64
	OwnerID            int64
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.Name,
		arg.Slug,
		arg.WorkspaceID,
		arg.SandboxWorkspaceID,
		arg.OwnerID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.AllowedOrigins,
		&i.SandboxWorkspaceID,
	)
	return i, err
}

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_users (
    app_id,
    user_id,
    external_id,
    environment
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, app_id, user_id, external_id, created_at, environment
`

type CreateAppUserParams struct {
	AppID       int64
	UserID      int64
	ExternalID  string
	Environment string
}

func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser,
		arg.AppID,
		arg.UserID,
		arg.ExternalID,
		arg.Environment,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.ExternalID,
		&i.CreatedAt,
		&i.Environment,
	)
	return i, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    app_id,
    idempotency_key,
    endpoint,
    status_code,
    response_body
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, app_id, idempotency_key, endpoint, status_code, response_body, created_at
`

type CreateIdempotencyKeyParams struct {
	AppID          int64
	IdempotencyKey string
	Endpoint       string
	StatusCode     int32
	ResponseBody   []byte
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.AppID,
		arg.IdempotencyKey,
		arg.Endpoint,
		arg.StatusCode,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.IdempotencyKey,
		&i.Endpoint,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (
    app_id,
    url,
    events,
    secret
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, app_id, url, events, secret, disabled_at, created_at
`

type CreateWebhookParams struct {
	AppID  int64
	Url    string
	Events []string
	Secret string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.AppID,
		arg.Url,
		arg.Events,
		arg.Secret,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Url,
		&i.Events,
		&i.Secret,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredEmptySandboxChannels = `-- name: DeleteExpiredEmptySandboxChannels :execrows
DELETE FROM channels c
USING apps a
WHERE c.workspace_id = a.sandbox_workspace_id
  AND c.created_at < $1
  AND NOT EXISTS (
    SELECT 1
    FROM messages m
    WHERE m.channel_id = c.id
  )
`

func (q *Queries) DeleteExpiredEmptySandboxChannels(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmptySandboxChannels, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredSandboxMessages = `-- name: DeleteExpiredSandboxMessages :execrows
DELETE FROM messages m
USING channels c, apps a
WHERE m.channel_id = c.id
  AND c.workspace_id = a.sandbox_workspace_id
  AND m.created_at < $1
`

func (q *Queries) DeleteExpiredSandboxMessages(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSandboxMessages, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableWebhook = `-- name: DisableWebhook :execrows
UPDATE webhooks
SET disabled_at = NOW()
WHERE id = $1
  AND app_id = $2
  AND disabled_at IS NULL
`

type DisableWebhookParams struct {
	ID    int64
	AppID int64
}

func (q *Queries) DisableWebhook(ctx context.Context, arg DisableWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableWebhook, arg.ID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, app_id, name, key_prefix, key_hash, is_sandbox, created_at, revoked_at, last_used_at, expires_at
FROM api_keys
WHERE key_prefix = $1
  AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.IsSandbox,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, name, slug, workspace_id, owner_id, created_at, allowed_origins, sandbox_workspace_id
FROM apps
WHERE id = $1
`

func (q *Queries) GetAppByID(ctx context.Context, id int64) (App, error) {
	row := q.db.QueryRow(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.AllowedOrigins,
		&i.SandboxWorkspaceID,
	)
	return i, err
}

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT id, name, slug, workspace_id, owner_id, created_at, allowed_origins, sandbox_workspace_id
FROM apps
WHERE slug = $1
`

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (App, error) {
	row := q.db.QueryRow(ctx, getAppBySlug, slug)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.AllowedOrigins,
		&i.SandboxWorkspaceID,
	)
	return i, err
}

const getAppUserByExternalID = `-- name: GetAppUserByExternalID :one
SELECT id, app_id, user_id, external_id, created_at, environment
FROM app_users
WHERE app_id = $1
  AND external_id = $2
  AND environment = $3
`

type GetAppUserByExternalIDParams struct {
	AppID       int64
	ExternalID  string
	Environment string
}

func (q *Queries) GetAppUserByExternalID(ctx context.Context, arg GetAppUserByExternalIDParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByExternalID, arg.AppID, arg.ExternalID, arg.Environment)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.ExternalID,
		&i.CreatedAt,
		&i.Environment,
	)
	return i, err
}

const getAppUserByUserID = `-- name: GetAppUserByUserID :one
SELECT id, app_id, user_id, external_id, created_at, environment
FROM app_users
WHERE app_id = $1
  AND user_id = $2
`

type GetAppUserByUserIDParams struct {
	AppID  int64
	UserID int64
}

func (q *Queries) GetAppUserByUserID(ctx context.Context, arg GetAppUserByUserIDParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByUserID, arg.AppID, arg.UserID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.UserID,
		&i.ExternalID,
		&i.CreatedAt,
		&i.Environment,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, app_id, idempotency_key, endpoint, status_code, response_body, created_at
FROM idempotency_keys
WHERE app_id = $1
  AND idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	AppID          int64
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.AppID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.IdempotencyKey,
		&i.Endpoint,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByApp = `-- name: ListAPIKeysByApp :many
SELECT id, app_id, name, key_prefix, key_hash, is_sandbox, created_at, revoked_at, last_used_at, expires_at
FROM api_keys
WHERE app_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByApp(ctx context.Context, appID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.IsSandbox,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppOriginEntries = `-- name: ListAppOriginEntries :many
SELECT id, workspace_id, sandbox_workspace_id, allowed_origins
FROM apps
`

type ListAppOriginEntriesRow struct {
	ID                 int64
	WorkspaceID        int64
	SandboxWorkspaceID int64
	AllowedOrigins     []string
}

func (q *Queries) ListAppOriginEntries(ctx context.Context) ([]ListAppOriginEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAppOriginEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppOriginEntriesRow
	for rows.Next() {
		var i ListAppOriginEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SandboxWorkspaceID,
			&i.AllowedOrigins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOwner = `-- name: ListAppsByOwner :many
SELECT id, name, slug, workspace_id, owner_id, created_at, allowed_origins, sandbox_workspace_id
FROM apps
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAppsByOwner(ctx context.Context, ownerID int64) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.WorkspaceID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.AllowedOrigins,
			&i.SandboxWorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByApp = `-- name: ListWebhooksByApp :many
SELECT id, app_id, url, events, secret, disabled_at, created_at
FROM webhooks
WHERE app_id = $1
  AND disabled_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByApp(ctx context.Context, appID int64) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Url,
			&i.Events,
			&i.Secret,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1
  AND app_id = $2
  AND revoked_at IS NULL
RETURNING id, app_id, name, key_prefix, key_hash, is_sandbox, created_at, revoked_at, last_used_at, expires_at
`

type RevokeAPIKeyParams struct {
	ID    int64
	AppID int64
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.AppID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.IsSandbox,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}

const updateAppAllowedOrigins = `-- name: UpdateAppAllowedOrigins :one
UPDATE apps
SET allowed_origins = $2
WHERE id = $1
RETURNING id, name, slug, workspace_id, owner_id, created_at, allowed_origins, sandbox_workspace_id
`

type UpdateAppAllowedOriginsParams struct {
	ID             int64
	AllowedOrigins []string
}

func (q *Queries) UpdateAppAllowedOrigins(ctx context.Context, arg UpdateAppAllowedOriginsParams) (App, error) {
	row := q.db.QueryRow(ctx, updateAppAllowedOrigins, arg.ID, arg.AllowedOrigins)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.AllowedOrigins,
		&i.SandboxWorkspaceID,
	)
	return i, err
}
