// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (
    message_id,
    uploader_id,
    object_key,
    file_name,
    mime_type,
    size_bytes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, message_id, uploader_id, object_key, file_name, mime_type, size_bytes, created_at
`

type CreateAttachmentParams struct {
	MessageID  int64
	UploaderID int64
	ObjectKey  string
	FileName   string
	MimeType   string
	SizeBytes  int64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.UploaderID,
		arg.ObjectKey,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UploaderID,
		&i.ObjectKey,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, message_id, uploader_id, object_key, file_name, mime_type, size_bytes, created_at
FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id int64) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UploaderID,
		&i.ObjectKey,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageInChannel = `-- name: GetMessageInChannel :one
SELECT
    m.id,
    m.channel_id,
    m.sender_id,
    m.content,
    m.created_at
FROM messages m
INNER JOIN channels c
    ON c.id = m.channel_id
WHERE m.id = $1
  AND m.channel_id = $2
  AND c.workspace_id = $3
`

type GetMessageInChannelParams struct {
	ID          int64
	ChannelID   int64
	WorkspaceID int64
}

func (q *Queries) GetMessageInChannel(ctx context.Context, arg GetMessageInChannelParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageInChannel, arg.ID, arg.ChannelID, arg.WorkspaceID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByMessage = `-- name: ListAttachmentsByMessage :many
SELECT id, message_id, uploader_id, object_key, file_name, mime_type, size_bytes, created_at
FROM attachments
WHERE message_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByMessage(ctx context.Context, messageID int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UploaderID,
			&i.ObjectKey,
			&i.FileName,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
