// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    user_id,
    app_id,
    action,
    method,
    path,
    ip_address,
    status_code
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateAuditLogParams struct {
	UserID     pgtype.Int8
	AppID      pgtype.Int8
	Action     string
	Method     string
	Path       string
	IpAddress  pgtype.Text
	StatusCode pgtype.Int4
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.UserID,
		arg.AppID,
		arg.Action,
		arg.Method,
		arg.Path,
		arg.IpAddress,
		arg.StatusCode,
	)
	return err
}
