// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountActiveSubscriptions = `-- name: AdminCountActiveSubscriptions :one
SELECT COUNT(*)::bigint
FROM app_subscriptions
WHERE status IN ('active', 'trialing')
`

func (q *Queries) AdminCountActiveSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountActiveSubscriptions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminListAppSubscriptions = `-- name: AdminListAppSubscriptions :many
SELECT
    s.app_id,
    a.name AS app_name,
    a.slug AS app_slug,
    s.plan_slug,
    p.name AS plan_name,
    s.status,
    s.current_period_end,
    COALESCE(u.messages_count, 0)::bigint AS messages_this_month
FROM app_subscriptions s
INNER JOIN apps a ON a.id = s.app_id
INNER JOIN plans p ON p.slug = s.plan_slug
LEFT JOIN usage_counters u
    ON u.app_id = s.app_id
   AND u.period_month = date_trunc('month', NOW())::date
ORDER BY s.updated_at DESC
LIMIT $1 OFFSET $2
`

type AdminListAppSubscriptionsParams struct {
	Limit  int32
	Offset int32
}

type AdminListAppSubscriptionsRow struct {
	AppID             int64
	AppName           string
	AppSlug           string
	PlanSlug          string
	PlanName          string
	Status            string
	CurrentPeriodEnd  pgtype.Timestamptz
	MessagesThisMonth int64
}

func (q *Queries) AdminListAppSubscriptions(ctx context.Context, arg AdminListAppSubscriptionsParams) ([]AdminListAppSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, adminListAppSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListAppSubscriptionsRow
	for rows.Next() {
		var i AdminListAppSubscriptionsRow
		if err := rows.Scan(
			&i.AppID,
			&i.AppName,
			&i.AppSlug,
			&i.PlanSlug,
			&i.PlanName,
			&i.Status,
			&i.CurrentPeriodEnd,
			&i.MessagesThisMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAppSubscription = `-- name: CreateAppSubscription :one
INSERT INTO app_subscriptions (
    app_id,
    plan_slug,
    status
)
VALUES ($1, $2, $3)
RETURNING id, app_id, plan_slug, status, stripe_customer_id, stripe_subscription_id, current_period_start, current_period_end, created_at, updated_at
`

type CreateAppSubscriptionParams struct {
	AppID    int64
	PlanSlug string
	Status   string
}

func (q *Queries) CreateAppSubscription(ctx context.Context, arg CreateAppSubscriptionParams) (AppSubscription, error) {
	row := q.db.QueryRow(ctx, createAppSubscription, arg.AppID, arg.PlanSlug, arg.Status)
	var i AppSubscription
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.PlanSlug,
		&i.Status,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppByWorkspaceID = `-- name: GetAppByWorkspaceID :one
SELECT id, name, slug, workspace_id, owner_id, created_at
FROM apps
WHERE workspace_id = $1
`

func (q *Queries) GetAppByWorkspaceID(ctx context.Context, workspaceID int64) (App, error) {
	row := q.db.QueryRow(ctx, getAppByWorkspaceID, workspaceID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getAppMessageUsage = `-- name: GetAppMessageUsage :one
SELECT messages_count
FROM usage_counters
WHERE app_id = $1
  AND period_month = date_trunc('month', NOW())::date
`

func (q *Queries) GetAppMessageUsage(ctx context.Context, appID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getAppMessageUsage, appID)
	var messages_count int64
	err := row.Scan(&messages_count)
	return messages_count, err
}

const getAppSubscription = `-- name: GetAppSubscription :one
SELECT
    s.id, s.app_id, s.plan_slug, s.status, s.stripe_customer_id, s.stripe_subscription_id, s.current_period_start, s.current_period_end, s.created_at, s.updated_at,
    p.name AS plan_name,
    p.price_cents,
    p.messages_limit,
    p.connections_limit,
    p.retention_days,
    p.webhooks_enabled,
    p.video_calls_enabled,
    p.moderation_enabled
FROM app_subscriptions s
INNER JOIN plans p ON p.slug = s.plan_slug
WHERE s.app_id = $1
`

type GetAppSubscriptionRow struct {
	ID                   int64
	AppID                int64
	PlanSlug             string
	Status               string
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	CurrentPeriodStart   pgtype.Timestamptz
	CurrentPeriodEnd     pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	PlanName             string
	PriceCents           int32
	MessagesLimit        int32
	ConnectionsLimit     int32
	RetentionDays        int32
	WebhooksEnabled      bool
	VideoCallsEnabled    bool
	ModerationEnabled    bool
}

func (q *Queries) GetAppSubscription(ctx context.Context, appID int64) (GetAppSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getAppSubscription, appID)
	var i GetAppSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.PlanSlug,
		&i.Status,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
		&i.PriceCents,
		&i.MessagesLimit,
		&i.ConnectionsLimit,
		&i.RetentionDays,
		&i.WebhooksEnabled,
		&i.VideoCallsEnabled,
		&i.ModerationEnabled,
	)
	return i, err
}

const getAppSubscriptionByStripeSubscriptionID = `-- name: GetAppSubscriptionByStripeSubscriptionID :one
SELECT id, app_id, plan_slug, status, stripe_customer_id, stripe_subscription_id, current_period_start, current_period_end, created_at, updated_at
FROM app_subscriptions
WHERE stripe_subscription_id = $1
`

func (q *Queries) GetAppSubscriptionByStripeSubscriptionID(ctx context.Context, stripeSubscriptionID pgtype.Text) (AppSubscription, error) {
	row := q.db.QueryRow(ctx, getAppSubscriptionByStripeSubscriptionID, stripeSubscriptionID)
	var i AppSubscription
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.PlanSlug,
		&i.Status,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT slug, name, price_cents, stripe_price_id, messages_limit, connections_limit, retention_days, webhooks_enabled, video_calls_enabled, moderation_enabled, created_at
FROM plans
WHERE slug = $1
`

func (q *Queries) GetPlan(ctx context.Context, slug string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, slug)
	var i Plan
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.PriceCents,
		&i.StripePriceID,
		&i.MessagesLimit,
		&i.ConnectionsLimit,
		&i.RetentionDays,
		&i.WebhooksEnabled,
		&i.VideoCallsEnabled,
		&i.ModerationEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformSetting = `-- name: GetPlatformSetting :one
SELECT value
FROM platform_settings
WHERE key = $1
`

func (q *Queries) GetPlatformSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getPlatformSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserStripeCustomerID = `-- name: GetUserStripeCustomerID :one
SELECT stripe_customer_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUserStripeCustomerID(ctx context.Context, id int64) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserStripeCustomerID, id)
	var stripe_customer_id pgtype.Text
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const incrementAppMessageUsage = `-- name: IncrementAppMessageUsage :one
INSERT INTO usage_counters (app_id, period_month, messages_count)
VALUES ($1, date_trunc('month', NOW())::date, 1)
ON CONFLICT (app_id, period_month)
DO UPDATE SET
    messages_count = usage_counters.messages_count + 1,
    updated_at = NOW()
RETURNING messages_count
`

func (q *Queries) IncrementAppMessageUsage(ctx context.Context, appID int64) (int64, error) {
	row := q.db.QueryRow(ctx, incrementAppMessageUsage, appID)
	var messages_count int64
	err := row.Scan(&messages_count)
	return messages_count, err
}

const listPlans = `-- name: ListPlans :many
SELECT slug, name, price_cents, stripe_price_id, messages_limit, connections_limit, retention_days, webhooks_enabled, video_calls_enabled, moderation_enabled, created_at
FROM plans
ORDER BY price_cents ASC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.PriceCents,
			&i.StripePriceID,
			&i.MessagesLimit,
			&i.ConnectionsLimit,
			&i.RetentionDays,
			&i.WebhooksEnabled,
			&i.VideoCallsEnabled,
			&i.ModerationEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStripeCustomerID = `-- name: SetUserStripeCustomerID :exec
UPDATE users
SET stripe_customer_id = $2
WHERE id = $1
  AND (stripe_customer_id IS NULL OR stripe_customer_id = '')
`

type SetUserStripeCustomerIDParams struct {
	ID               int64
	StripeCustomerID pgtype.Text
}

func (q *Queries) SetUserStripeCustomerID(ctx context.Context, arg SetUserStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, setUserStripeCustomerID, arg.ID, arg.StripeCustomerID)
	return err
}

const updateAppSubscription = `-- name: UpdateAppSubscription :one
UPDATE app_subscriptions
SET
    plan_slug = COALESCE($1, plan_slug),
    status = COALESCE($2, status),
    stripe_customer_id = COALESCE($3, stripe_customer_id),
    stripe_subscription_id = COALESCE($4, stripe_subscription_id),
    current_period_start = COALESCE($5, current_period_start),
    current_period_end = COALESCE($6, current_period_end),
    updated_at = NOW()
WHERE app_id = $7
RETURNING id, app_id, plan_slug, status, stripe_customer_id, stripe_subscription_id, current_period_start, current_period_end, created_at, updated_at
`

type UpdateAppSubscriptionParams struct {
	PlanSlug             pgtype.Text
	Status               pgtype.Text
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	CurrentPeriodStart   pgtype.Timestamptz
	CurrentPeriodEnd     pgtype.Timestamptz
	AppID                int64
}

func (q *Queries) UpdateAppSubscription(ctx context.Context, arg UpdateAppSubscriptionParams) (AppSubscription, error) {
	row := q.db.QueryRow(ctx, updateAppSubscription,
		arg.PlanSlug,
		arg.Status,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.AppID,
	)
	var i AppSubscription
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.PlanSlug,
		&i.Status,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatformSetting = `-- name: UpsertPlatformSetting :exec
INSERT INTO platform_settings (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
`

type UpsertPlatformSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) error {
	_, err := q.db.Exec(ctx, upsertPlatformSetting, arg.Key, arg.Value)
	return err
}
