// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calls.sql

package db

import (
	"context"
)

const addCallParticipant = `-- name: AddCallParticipant :one
INSERT INTO call_participants (
    call_id,
    user_id
)
VALUES (
    $1,
    $2
)
RETURNING id, call_id, user_id, joined_at, left_at
`

type AddCallParticipantParams struct {
	CallID int64
	UserID int64
}

func (q *Queries) AddCallParticipant(ctx context.Context, arg AddCallParticipantParams) (CallParticipant, error) {
	row := q.db.QueryRow(ctx, addCallParticipant, arg.CallID, arg.UserID)
	var i CallParticipant
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const countActiveCallParticipants = `-- name: CountActiveCallParticipants :one
SELECT COUNT(*)::bigint AS count
FROM call_participants
WHERE call_id = $1
  AND left_at IS NULL
`

func (q *Queries) CountActiveCallParticipants(ctx context.Context, callID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCallParticipants, callID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCall = `-- name: CreateCall :one
INSERT INTO calls (
    channel_id,
    workspace_id,
    initiator_id,
    status,
    mode
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, channel_id, workspace_id, initiator_id, status, created_at, ended_at, mode
`

type CreateCallParams struct {
	ChannelID   int64
	WorkspaceID int64
	InitiatorID int64
	Status      string
	Mode        string
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (Call, error) {
	row := q.db.QueryRow(ctx, createCall,
		arg.ChannelID,
		arg.WorkspaceID,
		arg.InitiatorID,
		arg.Status,
		arg.Mode,
	)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.WorkspaceID,
		&i.InitiatorID,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Mode,
	)
	return i, err
}

const createCallRecording = `-- name: CreateCallRecording :one
INSERT INTO call_recordings (
    call_id,
    started_by,
    metadata
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, call_id, started_by, started_at, ended_at, metadata
`

type CreateCallRecordingParams struct {
	CallID    int64
	StartedBy int64
	Metadata  []byte
}

func (q *Queries) CreateCallRecording(ctx context.Context, arg CreateCallRecordingParams) (CallRecording, error) {
	row := q.db.QueryRow(ctx, createCallRecording, arg.CallID, arg.StartedBy, arg.Metadata)
	var i CallRecording
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
	)
	return i, err
}

const endCallRecording = `-- name: EndCallRecording :one
UPDATE call_recordings
SET ended_at = NOW()
WHERE id = $1
  AND call_id = $2
  AND ended_at IS NULL
RETURNING id, call_id, started_by, started_at, ended_at, metadata
`

type EndCallRecordingParams struct {
	ID     int64
	CallID int64
}

func (q *Queries) EndCallRecording(ctx context.Context, arg EndCallRecordingParams) (CallRecording, error) {
	row := q.db.QueryRow(ctx, endCallRecording, arg.ID, arg.CallID)
	var i CallRecording
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
	)
	return i, err
}

const getActiveCallByChannel = `-- name: GetActiveCallByChannel :one
SELECT id, channel_id, workspace_id, initiator_id, status, created_at, ended_at, mode
FROM calls
WHERE channel_id = $1
  AND status IN ('ringing', 'active')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCallByChannel(ctx context.Context, channelID int64) (Call, error) {
	row := q.db.QueryRow(ctx, getActiveCallByChannel, channelID)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.WorkspaceID,
		&i.InitiatorID,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Mode,
	)
	return i, err
}

const getActiveCallParticipant = `-- name: GetActiveCallParticipant :one
SELECT id, call_id, user_id, joined_at, left_at
FROM call_participants
WHERE call_id = $1
  AND user_id = $2
  AND left_at IS NULL
`

type GetActiveCallParticipantParams struct {
	CallID int64
	UserID int64
}

func (q *Queries) GetActiveCallParticipant(ctx context.Context, arg GetActiveCallParticipantParams) (CallParticipant, error) {
	row := q.db.QueryRow(ctx, getActiveCallParticipant, arg.CallID, arg.UserID)
	var i CallParticipant
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getActiveCallRecording = `-- name: GetActiveCallRecording :one
SELECT id, call_id, started_by, started_at, ended_at, metadata
FROM call_recordings
WHERE call_id = $1
  AND ended_at IS NULL
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveCallRecording(ctx context.Context, callID int64) (CallRecording, error) {
	row := q.db.QueryRow(ctx, getActiveCallRecording, callID)
	var i CallRecording
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.StartedBy,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
	)
	return i, err
}

const getCallByID = `-- name: GetCallByID :one
SELECT id, channel_id, workspace_id, initiator_id, status, created_at, ended_at, mode
FROM calls
WHERE id = $1
`

func (q *Queries) GetCallByID(ctx context.Context, id int64) (Call, error) {
	row := q.db.QueryRow(ctx, getCallByID, id)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.WorkspaceID,
		&i.InitiatorID,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Mode,
	)
	return i, err
}

const listActiveCallParticipants = `-- name: ListActiveCallParticipants :many
SELECT id, call_id, user_id, joined_at, left_at
FROM call_participants
WHERE call_id = $1
  AND left_at IS NULL
ORDER BY joined_at ASC
`

func (q *Queries) ListActiveCallParticipants(ctx context.Context, callID int64) ([]CallParticipant, error) {
	rows, err := q.db.Query(ctx, listActiveCallParticipants, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CallParticipant
	for rows.Next() {
		var i CallParticipant
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.UserID,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMemberUserIDs = `-- name: ListChannelMemberUserIDs :many
SELECT user_id
FROM channel_members
WHERE channel_id = $1
`

func (q *Queries) ListChannelMemberUserIDs(ctx context.Context, channelID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listChannelMemberUserIDs, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCallParticipantLeft = `-- name: MarkCallParticipantLeft :one
UPDATE call_participants
SET left_at = NOW()
WHERE call_id = $1
  AND user_id = $2
  AND left_at IS NULL
RETURNING id, call_id, user_id, joined_at, left_at
`

type MarkCallParticipantLeftParams struct {
	CallID int64
	UserID int64
}

func (q *Queries) MarkCallParticipantLeft(ctx context.Context, arg MarkCallParticipantLeftParams) (CallParticipant, error) {
	row := q.db.QueryRow(ctx, markCallParticipantLeft, arg.CallID, arg.UserID)
	var i CallParticipant
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const updateCallStatus = `-- name: UpdateCallStatus :one
UPDATE calls
SET status = $2,
    ended_at = CASE WHEN $2 = 'ended' THEN NOW() ELSE ended_at END
WHERE id = $1
RETURNING id, channel_id, workspace_id, initiator_id, status, created_at, ended_at, mode
`

type UpdateCallStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateCallStatus(ctx context.Context, arg UpdateCallStatusParams) (Call, error) {
	row := q.db.QueryRow(ctx, updateCallStatus, arg.ID, arg.Status)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.WorkspaceID,
		&i.InitiatorID,
		&i.Status,
		&i.CreatedAt,
		&i.EndedAt,
		&i.Mode,
	)
	return i, err
}
