// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_roles.sql

package db

import (
	"context"
)

const getChannelRole = `-- name: GetChannelRole :one
SELECT
    id,
    channel_id,
    user_id,
    role,
    created_at
FROM channel_roles
WHERE channel_id = $1 AND user_id = $2
`

type GetChannelRoleParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) GetChannelRole(ctx context.Context, arg GetChannelRoleParams) (ChannelRole, error) {
	row := q.db.QueryRow(ctx, getChannelRole, arg.ChannelID, arg.UserID)
	var i ChannelRole
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertChannelRole = `-- name: UpsertChannelRole :exec
INSERT INTO channel_roles (
    channel_id,
    user_id,
    role
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (channel_id, user_id)
DO UPDATE SET role = EXCLUDED.role
`

type UpsertChannelRoleParams struct {
	ChannelID int64
	UserID    int64
	Role      string
}

func (q *Queries) UpsertChannelRole(ctx context.Context, arg UpsertChannelRoleParams) error {
	_, err := q.db.Exec(ctx, upsertChannelRole, arg.ChannelID, arg.UserID, arg.Role)
	return err
}
