// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members (
    channel_id,
    user_id
)
VALUES (
    $1,
    $2
)
`

type AddChannelMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.Exec(ctx, addChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
    name,
    owner_id
)
VALUES (
    $1,
    $2
)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateChannelParams struct {
	Name    string
	OwnerID int64
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.Name, arg.OwnerID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, owner_id, created_at, updated_at
FROM channels
WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelMember = `-- name: GetChannelMember :one
SELECT id, channel_id, user_id, created_at, updated_at
FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type GetChannelMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) GetChannelMember(ctx context.Context, arg GetChannelMemberParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, getChannelMember, arg.ChannelID, arg.UserID)
	var i ChannelMember
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelsByUser = `-- name: GetChannelsByUser :many
SELECT
    c.id,
    c.name,
    c.owner_id,
    c.created_at
FROM channels c
INNER JOIN channel_members cm
    ON c.id = cm.channel_id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

type GetChannelsByUserRow struct {
	ID        int64
	Name      string
	OwnerID   int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetChannelsByUser(ctx context.Context, userID int64) ([]GetChannelsByUserRow, error) {
	rows, err := q.db.Query(ctx, getChannelsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelsByUserRow
	for rows.Next() {
		var i GetChannelsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS(
    SELECT 1
    FROM channel_members
    WHERE channel_id = $1 AND user_id = $2
)::boolean AS is_member
`

type IsChannelMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const removeChannelMember = `-- name: RemoveChannelMember :exec
DELETE FROM channel_members
WHERE channel_id = $1 AND user_id = $2
`

type RemoveChannelMemberParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error {
	_, err := q.db.Exec(ctx, removeChannelMember, arg.ChannelID, arg.UserID)
	return err
}
