// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    channel_id,
    sender_id,
    content
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, channel_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ChannelID int64
	SenderID  int64
	Content   string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChannelID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT
    m.id,
    m.channel_id,
    m.sender_id,
    m.content,
    m.created_at,
    u.username
FROM messages m
INNER JOIN users u
    ON m.sender_id = u.id
WHERE m.channel_id = $1
ORDER BY m.created_at ASC
LIMIT $2 OFFSET $3
`

type GetChannelMessagesParams struct {
	ChannelID int64
	Limit     int32
	Offset    int32
}

type GetChannelMessagesRow struct {
	ID        int64
	ChannelID int64
	SenderID  int64
	Content   string
	CreatedAt pgtype.Timestamptz
	Username  string
}

func (q *Queries) GetChannelMessages(ctx context.Context, arg GetChannelMessagesParams) ([]GetChannelMessagesRow, error) {
	rows, err := q.db.Query(ctx, getChannelMessages, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMessagesRow
	for rows.Next() {
		var i GetChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, channel_id, sender_id, content, created_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
