// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID         int64
	MessageID  int64
	UploaderID int64
	ObjectKey  string
	FileName   string
	MimeType   string
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
}

type Call struct {
	ID          int64
	ChannelID   int64
	WorkspaceID int64
	InitiatorID int64
	Status      string
	CreatedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
}

type CallParticipant struct {
	ID       int64
	CallID   int64
	UserID   int64
	JoinedAt pgtype.Timestamptz
	LeftAt   pgtype.Timestamptz
}

type Channel struct {
	ID          int64
	Name        string
	OwnerID     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	WorkspaceID int64
	IsReadOnly  bool
}

type ChannelMember struct {
	ID        int64
	ChannelID int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ChannelRole struct {
	ID        int64
	ChannelID int64
	UserID    int64
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID        int64
	ChannelID int64
	SenderID  int64
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Notification struct {
	ID        int64
	UserID    int64
	Type      string
	Title     string
	Body      string
	Data      []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID        int64
	Name      string
	Slug      string
	OwnerID   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	ID          int64
	WorkspaceID int64
	UserID      int64
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
