// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID        int64
	Name      string
	OwnerID   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ChannelMember struct {
	ID        int64
	ChannelID int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Message struct {
	ID        int64
	ChannelID int64
	SenderID  int64
	Content   string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
