// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64
	AppID      int64
	Name       string
	KeyPrefix  string
	KeyHash    string
	IsSandbox  bool
	CreatedAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type App struct {
	ID          int64
	Name        string
	Slug        string
	WorkspaceID int64
	OwnerID     int64
	CreatedAt   pgtype.Timestamptz
}

type AppSubscription struct {
	ID                   int64
	AppID                int64
	PlanSlug             string
	Status               string
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	CurrentPeriodStart   pgtype.Timestamptz
	CurrentPeriodEnd     pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type AppUser struct {
	ID         int64
	AppID      int64
	UserID     int64
	ExternalID string
	CreatedAt  pgtype.Timestamptz
}

type Attachment struct {
	ID         int64
	MessageID  int64
	UploaderID int64
	ObjectKey  string
	FileName   string
	MimeType   string
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
}

type AuditLog struct {
	ID         int64
	UserID     pgtype.Int8
	AppID      pgtype.Int8
	Action     string
	Method     string
	Path       string
	IpAddress  pgtype.Text
	StatusCode pgtype.Int4
	CreatedAt  pgtype.Timestamptz
}

type Call struct {
	ID          int64
	ChannelID   int64
	WorkspaceID int64
	InitiatorID int64
	Status      string
	CreatedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	Mode        string
}

type CallParticipant struct {
	ID       int64
	CallID   int64
	UserID   int64
	JoinedAt pgtype.Timestamptz
	LeftAt   pgtype.Timestamptz
}

type CallRecording struct {
	ID        int64
	CallID    int64
	StartedBy int64
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	Metadata  []byte
}

type Channel struct {
	ID          int64
	Name        string
	OwnerID     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	WorkspaceID int64
	IsReadOnly  bool
}

type ChannelMember struct {
	ID        int64
	ChannelID int64
	UserID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ChannelRole struct {
	ID        int64
	ChannelID int64
	UserID    int64
	Role      string
	CreatedAt pgtype.Timestamptz
}

type IdempotencyKey struct {
	ID             int64
	AppID          int64
	IdempotencyKey string
	Endpoint       string
	StatusCode     int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
}

type Message struct {
	ID        int64
	ChannelID int64
	SenderID  int64
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Notification struct {
	ID        int64
	UserID    int64
	Type      string
	Title     string
	Body      string
	Data      []byte
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Plan struct {
	Slug              string
	Name              string
	PriceCents        int32
	StripePriceID     pgtype.Text
	MessagesLimit     int32
	ConnectionsLimit  int32
	RetentionDays     int32
	WebhooksEnabled   bool
	VideoCallsEnabled bool
	ModerationEnabled bool
	CreatedAt         pgtype.Timestamptz
	IsActive          bool
	IsHighlighted     bool
	SortOrder         int32
	Description       string
	UpdatedAt         pgtype.Timestamptz
}

type PlatformSetting struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type RevokedToken struct {
	Jti       string
	UserID    int64
	RevokedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type UsageCounter struct {
	ID            int64
	AppID         int64
	PeriodMonth   pgtype.Date
	MessagesCount int64
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID                  int64
	Email               string
	Username            string
	PasswordHash        string
	CreatedAt           pgtype.Timestamptz
	PlatformRole        string
	SuspendedAt         pgtype.Timestamptz
	TokensInvalidatedAt pgtype.Timestamptz
	StripeCustomerID    pgtype.Text
}

type Webhook struct {
	ID         int64
	AppID      int64
	Url        string
	Events     []string
	Secret     string
	DisabledAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Workspace struct {
	ID        int64
	Name      string
	Slug      string
	OwnerID   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	ID          int64
	WorkspaceID int64
	UserID      int64
	Role        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
