// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platformadmin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountApps = `-- name: AdminCountApps :one
SELECT COUNT(*)::bigint AS count FROM apps
`

func (q *Queries) AdminCountApps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountApps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*)::bigint AS count FROM users
`

func (q *Queries) AdminCountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountWorkspaces = `-- name: AdminCountWorkspaces :one
SELECT COUNT(*)::bigint AS count FROM workspaces
`

func (q *Queries) AdminCountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserApps = `-- name: CountUserApps :one
SELECT COUNT(*)::bigint AS count
FROM apps
WHERE owner_id = $1
`

func (q *Queries) CountUserApps(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserApps, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserWorkspaces = `-- name: CountUserWorkspaces :one
SELECT COUNT(*)::bigint AS count
FROM workspace_members
WHERE user_id = $1
`

func (q *Queries) CountUserWorkspaces(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserWorkspaces, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceChannels = `-- name: CountWorkspaceChannels :one
SELECT COUNT(*)::bigint AS count
FROM channels
WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceChannels(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceChannels, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceMembers = `-- name: CountWorkspaceMembers :one
SELECT COUNT(*)::bigint AS count
FROM workspace_members
WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceMembers(ctx context.Context, workspaceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMembers, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserAdmin = `-- name: GetUserAdmin :one
SELECT
    id,
    email,
    username,
    platform_role,
    suspended_at,
    tokens_invalidated_at,
    created_at
FROM users
WHERE id = $1
`

type GetUserAdminRow struct {
	ID                  int64
	Email               string
	Username            string
	PlatformRole        string
	SuspendedAt         pgtype.Timestamptz
	TokensInvalidatedAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetUserAdmin(ctx context.Context, id int64) (GetUserAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserAdmin, id)
	var i GetUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceAdmin = `-- name: GetWorkspaceAdmin :one
SELECT
    id,
    name,
    slug,
    owner_id,
    created_at,
    updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceAdmin(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceAdmin, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppsAdmin = `-- name: ListAppsAdmin :many
SELECT
    a.id,
    a.name,
    a.slug,
    a.workspace_id,
    a.owner_id,
    a.created_at,
    u.email AS owner_email
FROM apps a
INNER JOIN users u ON u.id = a.owner_id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAppsAdminParams struct {
	Limit  int32
	Offset int32
}

type ListAppsAdminRow struct {
	ID          int64
	Name        string
	Slug        string
	WorkspaceID int64
	OwnerID     int64
	CreatedAt   pgtype.Timestamptz
	OwnerEmail  string
}

func (q *Queries) ListAppsAdmin(ctx context.Context, arg ListAppsAdminParams) ([]ListAppsAdminRow, error) {
	rows, err := q.db.Query(ctx, listAppsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppsAdminRow
	for rows.Next() {
		var i ListAppsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.WorkspaceID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsAdmin = `-- name: ListAuditLogsAdmin :many
SELECT
    id,
    user_id,
    app_id,
    action,
    method,
    path,
    ip_address,
    status_code,
    created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsAdminParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuditLogsAdmin(ctx context.Context, arg ListAuditLogsAdminParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.Action,
			&i.Method,
			&i.Path,
			&i.IpAddress,
			&i.StatusCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT
    id,
    email,
    username,
    platform_role,
    suspended_at,
    created_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersAdminParams struct {
	Limit  int32
	Offset int32
}

type ListUsersAdminRow struct {
	ID           int64
	Email        string
	Username     string
	PlatformRole string
	SuspendedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PlatformRole,
			&i.SuspendedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesAdmin = `-- name: ListWorkspacesAdmin :many
SELECT
    id,
    name,
    slug,
    owner_id,
    created_at,
    updated_at
FROM workspaces
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWorkspacesAdminParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListWorkspacesAdmin(ctx context.Context, arg ListWorkspacesAdminParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteUserToAdminByEmail = `-- name: PromoteUserToAdminByEmail :one
UPDATE users
SET platform_role = 'admin'
WHERE LOWER(email) = LOWER($1)
  AND platform_role <> 'admin'
RETURNING id, email, username, platform_role, suspended_at, tokens_invalidated_at, created_at
`

type PromoteUserToAdminByEmailRow struct {
	ID                  int64
	Email               string
	Username            string
	PlatformRole        string
	SuspendedAt         pgtype.Timestamptz
	TokensInvalidatedAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) PromoteUserToAdminByEmail(ctx context.Context, lower string) (PromoteUserToAdminByEmailRow, error) {
	row := q.db.QueryRow(ctx, promoteUserToAdminByEmail, lower)
	var i PromoteUserToAdminByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchUsersAdmin = `-- name: SearchUsersAdmin :many
SELECT
    id,
    email,
    username,
    platform_role,
    suspended_at,
    created_at
FROM users
WHERE email ILIKE '%' || $3::text || '%'
   OR username ILIKE '%' || $3::text || '%'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchUsersAdminParams struct {
	Limit  int32
	Offset int32
	Search string
}

type SearchUsersAdminRow struct {
	ID           int64
	Email        string
	Username     string
	PlatformRole string
	SuspendedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) SearchUsersAdmin(ctx context.Context, arg SearchUsersAdminParams) ([]SearchUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdmin, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersAdminRow
	for rows.Next() {
		var i SearchUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PlatformRole,
			&i.SuspendedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendUser = `-- name: SuspendUser :one
UPDATE users
SET
    suspended_at = NOW(),
    tokens_invalidated_at = NOW()
WHERE id = $1
RETURNING id, email, username, platform_role, suspended_at, tokens_invalidated_at, created_at
`

type SuspendUserRow struct {
	ID                  int64
	Email               string
	Username            string
	PlatformRole        string
	SuspendedAt         pgtype.Timestamptz
	TokensInvalidatedAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) SuspendUser(ctx context.Context, id int64) (SuspendUserRow, error) {
	row := q.db.QueryRow(ctx, suspendUser, id)
	var i SuspendUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const unsuspendUser = `-- name: UnsuspendUser :one
UPDATE users
SET suspended_at = NULL
WHERE id = $1
RETURNING id, email, username, platform_role, suspended_at, tokens_invalidated_at, created_at
`

type UnsuspendUserRow struct {
	ID                  int64
	Email               string
	Username            string
	PlatformRole        string
	SuspendedAt         pgtype.Timestamptz
	TokensInvalidatedAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UnsuspendUser(ctx context.Context, id int64) (UnsuspendUserRow, error) {
	row := q.db.QueryRow(ctx, unsuspendUser, id)
	var i UnsuspendUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPlatformRole = `-- name: UpdateUserPlatformRole :one
UPDATE users
SET platform_role = $2
WHERE id = $1
RETURNING id, email, username, platform_role, suspended_at, tokens_invalidated_at, created_at
`

type UpdateUserPlatformRoleParams struct {
	ID           int64
	PlatformRole string
}

type UpdateUserPlatformRoleRow struct {
	ID                  int64
	Email               string
	Username            string
	PlatformRole        string
	SuspendedAt         pgtype.Timestamptz
	TokensInvalidatedAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateUserPlatformRole(ctx context.Context, arg UpdateUserPlatformRoleParams) (UpdateUserPlatformRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserPlatformRole, arg.ID, arg.PlatformRole)
	var i UpdateUserPlatformRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
		&i.CreatedAt,
	)
	return i, err
}
