// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS(
    SELECT 1
    FROM revoked_tokens
    WHERE jti = $1
)::boolean AS revoked
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, jti)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const revokeToken = `-- name: RevokeToken :exec
INSERT INTO revoked_tokens (
    jti,
    user_id,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (jti) DO NOTHING
`

type RevokeTokenParams struct {
	Jti       string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.Exec(ctx, revokeToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}
