// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,
    password_hash
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, email, username, password_hash, created_at, platform_role, suspended_at, tokens_invalidated_at
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
	)
	return i, err
}

const getUserAuthState = `-- name: GetUserAuthState :one
SELECT
    id,
    email,
    platform_role,
    suspended_at,
    tokens_invalidated_at
FROM users
WHERE id = $1
`

type GetUserAuthStateRow struct {
	ID                  int64
	Email               string
	PlatformRole        string
	SuspendedAt         pgtype.Timestamptz
	TokensInvalidatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserAuthState(ctx context.Context, id int64) (GetUserAuthStateRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthState, id)
	var i GetUserAuthStateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, created_at, platform_role, suspended_at, tokens_invalidated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, created_at, platform_role, suspended_at, tokens_invalidated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, created_at, platform_role, suspended_at, tokens_invalidated_at
FROM users
WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET username = $2
WHERE id = $1
RETURNING id, email, username, password_hash, created_at, platform_role, suspended_at, tokens_invalidated_at
`

type UpdateUserProfileParams struct {
	ID       int64
	Username string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.PlatformRole,
		&i.SuspendedAt,
		&i.TokensInvalidatedAt,
	)
	return i, err
}
