// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (
    workspace_id,
    user_id,
    role
)
VALUES (
    $1,
    $2,
    $3
)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID int64
	UserID      int64
	Role        string
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    name,
    slug,
    owner_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, slug, owner_id, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name    string
	Slug    string
	OwnerID int64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT
    id,
    name,
    slug,
    owner_id,
    created_at,
    updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT
    id,
    name,
    slug,
    owner_id,
    created_at,
    updated_at
FROM workspaces
WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspacesByUser = `-- name: GetWorkspacesByUser :many
SELECT
    w.id,
    w.name,
    w.slug,
    w.owner_id,
    w.created_at
FROM workspaces w
INNER JOIN workspace_members wm
    ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY w.created_at DESC
`

type GetWorkspacesByUserRow struct {
	ID        int64
	Name      string
	Slug      string
	OwnerID   int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetWorkspacesByUser(ctx context.Context, userID int64) ([]GetWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, getWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspacesByUserRow
	for rows.Next() {
		var i GetWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isWorkspaceMember = `-- name: IsWorkspaceMember :one
SELECT EXISTS(
    SELECT 1
    FROM workspace_members
    WHERE workspace_id = $1 AND user_id = $2
)::boolean AS is_member
`

type IsWorkspaceMemberParams struct {
	WorkspaceID int64
	UserID      int64
}

func (q *Queries) IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
