// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (
    workspace_id,
    user_id,
    role
)
VALUES (
    $1,
    $2,
    $3
)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID int64
	UserID      int64
	Role        string
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    name,
    slug,
    owner_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, slug, owner_id, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name    string
	Slug    string
	OwnerID int64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT
    id,
    name,
    slug,
    owner_id,
    created_at,
    updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT
    id,
    name,
    slug,
    owner_id,
    created_at,
    updated_at
FROM workspaces
WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT
    id,
    workspace_id,
    user_id,
    role,
    created_at,
    updated_at
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID int64
	UserID      int64
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMemberByUsername = `-- name: GetWorkspaceMemberByUsername :one
SELECT
    wm.user_id,
    u.username,
    u.email
FROM workspace_members wm
INNER JOIN users u
    ON u.id = wm.user_id
WHERE wm.workspace_id = $1 AND LOWER(u.username) = LOWER($2)
`

type GetWorkspaceMemberByUsernameParams struct {
	WorkspaceID int64
	Lower       string
}

type GetWorkspaceMemberByUsernameRow struct {
	UserID   int64
	Username string
	Email    string
}

func (q *Queries) GetWorkspaceMemberByUsername(ctx context.Context, arg GetWorkspaceMemberByUsernameParams) (GetWorkspaceMemberByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberByUsername, arg.WorkspaceID, arg.Lower)
	var i GetWorkspaceMemberByUsernameRow
	err := row.Scan(&i.UserID, &i.Username, &i.Email)
	return i, err
}

const getWorkspacesByUser = `-- name: GetWorkspacesByUser :many
SELECT
    w.id,
    w.name,
    w.slug,
    w.owner_id,
    w.created_at,
    wm.role
FROM workspaces w
INNER JOIN workspace_members wm
    ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY w.created_at DESC
`

type GetWorkspacesByUserRow struct {
	ID        int64
	Name      string
	Slug      string
	OwnerID   int64
	CreatedAt pgtype.Timestamptz
	Role      string
}

func (q *Queries) GetWorkspacesByUser(ctx context.Context, userID int64) ([]GetWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, getWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspacesByUserRow
	for rows.Next() {
		var i GetWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isWorkspaceMember = `-- name: IsWorkspaceMember :one
SELECT EXISTS(
    SELECT 1
    FROM workspace_members
    WHERE workspace_id = $1 AND user_id = $2
)::boolean AS is_member
`

type IsWorkspaceMemberParams struct {
	WorkspaceID int64
	UserID      int64
}

func (q *Queries) IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT
    wm.id,
    wm.workspace_id,
    wm.user_id,
    wm.role,
    wm.created_at,
    u.username,
    u.email
FROM workspace_members wm
INNER JOIN users u
    ON u.id = wm.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at ASC
`

type ListWorkspaceMembersRow struct {
	ID          int64
	WorkspaceID int64
	UserID      int64
	Role        string
	CreatedAt   pgtype.Timestamptz
	Username    string
	Email       string
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID int64) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID int64
	UserID      int64
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members
SET role = $3, updated_at = NOW()
WHERE workspace_id = $1 AND user_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID int64
	UserID      int64
	Role        string
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}
